### PR TITLE
Have toc_only return an empty string when toc is disabled

### PR DESCRIPTION
**Pull request by gandalf3**

### CODE REVIEW

**Comment by toshimaru** [comment]
I'm gonna add tests for this change. Let's get this merged.

**Comment by toshimaru** [comment]
@gandalf3 Thanks for reporting issue and sending PR ❤️ 
[v0.10.0](https://github.com/toshimaru/jekyll-toc/releases/tag/v0.10.0) has been released!!

**Comment by gandalf3** [comment]
@toshimaru Awesome, thanks!
By the way, I'm not sure if you saw my other PR: https://github.com/toshimaru/jekyll-toc/pull/75?

**Comment by toshimaru** [comment]
> if you saw my other PR: #75?

I'm still considering how it should be implemented..., Hold on please. 🙏

**Comment by gandalf3** [comment]
Of course, no rush!

**Pull request merged**
