### PR TITLE
Fix invalid toc HTML (Element "ul" not allowed as child of element "ul" in this context.)

### LINKED ISSUE #25: Invalid HTML
Hey, there.

So, in Bootstrap v4-dev we switched to your plugin.

I notice that the generated HTML is invalid.

See for example https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/about/brand.md

The HTML we get is the following, which is invalid:

```html
            <ul class="section-nav">
<ul>
<li class="toc-entry toc-h2"><a href="#contents">Contents</a></li>
<li class="toc-entry toc-h2"><a href="#mark-and-logo">Mark and logo</a></li>
</ul>
<li class="toc-entry toc-h1"><a href="#bootstrap">Bootstrap</a></li>
<li class="toc-entry toc-h1"><a href="#bootstrap-1">Bootstrap</a>
<ul>
<li class="toc-entry toc-h2"><a href="#download-mark">Download mark</a></li>
<li class="toc-entry toc-h2"><a href="#name">Name</a>
<ul>
<li class="toc-entry toc-h3"><a href="#bootstrap-2">Bootstrap</a></li>
<li class="toc-entry toc-h3"><a href="#bootstrap-3">BootStrap</a></li>
<li class="toc-entry toc-h3"><a href="#twitter-bootstrap">Twitter Bootstrap</a></li>
</ul>
</li>
<li class="toc-entry toc-h2"><a href="#colors">Colors</a></li>
</ul>
</li>
</ul>
```

/CC @mdo @johann-S

### PR DESCRIPTION
**Pull request by toshimaru**
Fixes #25

Fix HTMLlint error.

```
Element "ul" not allowed as child of element "ul" in this context. (Suppressing further errors from this subtree.)
```

ref. https://github.com/toshimaru/jekyll-toc/issues/25#issuecomment-333315235

### CODE REVIEW

**Comment by XhmikosR** [comment]
@toshimaru: are you blocked by the code climate issue?

**Comment by toshimaru** [comment]
nope, I found a bug in this implementation. still thinking how to deal with it. :(

**Comment by toshimaru** [comment]
@XhmikosR Hey, I fixed a bug and am gonna release this in few days. (as RC version)

**Comment by XhmikosR** [comment]
@toshimaru: thanks! I've been following the progress already :)

**Pull request merged**
