### PR TITLE
Update parser.rb

### LINKED ISSUE #25: Invalid HTML
Hey, there.

So, in Bootstrap v4-dev we switched to your plugin.

I notice that the generated HTML is invalid.

See for example https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/about/brand.md

The HTML we get is the following, which is invalid:

```html
            <ul class="section-nav">
<ul>
<li class="toc-entry toc-h2"><a href="#contents">Contents</a></li>
<li class="toc-entry toc-h2"><a href="#mark-and-logo">Mark and logo</a></li>
</ul>
<li class="toc-entry toc-h1"><a href="#bootstrap">Bootstrap</a></li>
<li class="toc-entry toc-h1"><a href="#bootstrap-1">Bootstrap</a>
<ul>
<li class="toc-entry toc-h2"><a href="#download-mark">Download mark</a></li>
<li class="toc-entry toc-h2"><a href="#name">Name</a>
<ul>
<li class="toc-entry toc-h3"><a href="#bootstrap-2">Bootstrap</a></li>
<li class="toc-entry toc-h3"><a href="#bootstrap-3">BootStrap</a></li>
<li class="toc-entry toc-h3"><a href="#twitter-bootstrap">Twitter Bootstrap</a></li>
</ul>
</li>
<li class="toc-entry toc-h2"><a href="#colors">Colors</a></li>
</ul>
</li>
</ul>
```

/CC @mdo @johann-S

### PR DESCRIPTION
**Pull request by XhmikosR**
Trying to fix HTML validation errors.

Fixes #25 

/CC @toshimaru

### CODE REVIEW

**Comment by toshimaru** [comment]
@XhmikosR Thank you for sending PR ❗️ 

Could you add test to make sure issue #25 is surely fixed.

**Comment by XhmikosR** [comment]
I'm not very familiar with Ruby; I just tested this change and fixes our issue.

**Comment by XhmikosR** [comment]
That means that I take no responsibility if it breaks something else :)

**Comment by toshimaru** [comment]
:ok:

I added a comment here: https://github.com/toshimaru/jekyll-toc/issues/25#issuecomment-333315002

**Comment by XhmikosR** [comment]
See #33

**Pull request closed without merging**
